Repository David0406/MSIT04, pull requests merged in 2021-10, with the labels that each got.

#1 change header size
  ReserverRideVar01/wwwroot/css/style.css
Labels: enhancement

#2 David product list view
  ReserverRideVar01/Views/Product/List.cshtml
Labels: bug, enhancement

#4 add user login function
  ReserverRideVar01/Controllers/HomeController.cs
  ReserverRideVar01/DbContext/MSITDbcontext.cs
  ReserverRideVar01/Models/Member.cs
  ReserverRideVar01/ViewModels/CLoginViewModel.cs
  ReserverRideVar01/Views/Home/Longin.cshtml
Labels: documentation
